### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by clarityzzz** [masterdoctor/LineageOS-p8lite-community#14]
Always shows off and won't work
BT adress is also unavailable in Status, in about phone

**Comment by ClassyLion** [comment]
+1
If i try to turn of bluetooth, it goes to on state and becomes gray. Then it cant be clicked and bluetooth doesnt turn on.

**Comment by masterdoctor** [comment]
We have disabled Bluetooth because of issues with building. We're still looking into it but this is a known issue.

**Comment by masterdoctor** [comment]
@XePeleato It seems we're missing a required library `sap-api-java-static` which appears to be a kernel library?
https://forum.xda-developers.com/showpost.php?s=85af4c936e964d933cc55ae09f6c17c1&p=66257628&postcount=3033

**Comment by XePeleato** [comment]
@masterdoctor I don't know what a kernel library is. `sap-api-**java**-static` Is a protobuf and the error appears because we are using a precompiled `librilutils` so this doesn't get compiled. The code is here https://android.googlesource.com/platform/hardware/ril/+/master/librilutils/proto/ just make it visible to ninja and the error will disappear.

**Comment by masterdoctor** [comment]
Oh okay.

**Comment by m3shat** [comment]
in syslog: 
BluetoothManagerService: Fail to bind to: Intent { act=android.bluetooth.IBluetooth }
maybe this helps a bit

**Comment by masterdoctor** [comment]
That's because we've removed the Bluetooth.apk, @m3shat
